version: "3.7"
services:
    laravel-app:
      build:
        args:
          user: ${USER}
          uid: ${UID}
        context: ./
        dockerfile: Dockerfile
      image: laravel-app
      container_name: laravel-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ${PATH_PROJECT}:/var/www

    mysql-db:
      image: mysql:8.0
      container_name: mysql-db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      ports:
       - "3306:3306"


    webserver-nginx:
      image: nginx:1.17-alpine
      container_name: webserver-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ${PATH_PROJECT}:/var/www
        - ./nginx:/etc/nginx/conf.d

# networks:
#       my_network:
#         driver: bridge